# Before your start:
- Read the README.md file
- Comment as much as you can and use the resources in the README.md file
- Happy learning!

In [87]:
# Import your libraries:
import pandas as pd
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn import metrics

# Challenge 1 - Explore the Scikit-Learn Datasets

Before starting to work on our own datasets, let's first explore the datasets that are included in this Python library. These datasets have been cleaned and formatted for use in ML algorithms.

First, we will load the diabetes dataset. Do this in the cell below by importing the datasets and then loading the dataset  to the `diabetes` variable using the `load_diabetes()` function.

In [2]:
# Your code here:
from sklearn.datasets import load_diabetes


Let's explore this variable by looking at the different attributes. Do this by looking at the `keys()` of this variable.

The next step is to read the description of the dataset. Print the description in the cell below using the `DESCR` attribute of the `diabetes` variable

In [4]:
# Your code here:
print(load_diabetes().get('DESCR'))


.. _diabetes_dataset:

Diabetes dataset
----------------

Ten baseline variables, age, sex, body mass index, average blood
pressure, and six blood serum measurements were obtained for each of n =
442 diabetes patients, as well as the response of interest, a
quantitative measure of disease progression one year after baseline.

**Data Set Characteristics:**

  :Number of Instances: 442

  :Number of Attributes: First 10 columns are numeric predictive values

  :Target: Column 11 is a quantitative measure of disease progression one year after baseline

  :Attribute Information:
      - age     age in years
      - sex
      - bmi     body mass index
      - bp      average blood pressure
      - s1      tc, T-Cells (a type of white blood cells)
      - s2      ldl, low-density lipoproteins
      - s3      hdl, high-density lipoproteins
      - s4      tch, thyroid stimulating hormone
      - s5      ltg, lamotrigine
      - s6      glu, blood sugar level

Note: Each of these 10 feature va

What are the variables in this dataset according to the description? List them in the markdown cell below

In [7]:
diabetes = pd.DataFrame(load_diabetes().data, columns=load_diabetes().feature_names)
diabetes.head()

age       sex       bmi        bp        s1        s2        s3  \
0  0.038076  0.050680  0.061696  0.021872 -0.044223 -0.034821 -0.043401   
1 -0.001882 -0.044642 -0.051474 -0.026328 -0.008449 -0.019163  0.074412   
2  0.085299  0.050680  0.044451 -0.005671 -0.045599 -0.034194 -0.032356   
3 -0.089063 -0.044642 -0.011595 -0.036656  0.012191  0.024991 -0.036038   
4  0.005383 -0.044642 -0.036385  0.021872  0.003935  0.015596  0.008142   

         s4        s5        s6  
0 -0.002592  0.019908 -0.017646  
1 -0.039493 -0.068330 -0.092204  
2 -0.002592  0.002864 -0.025930  
3  0.034309  0.022692 -0.009362  
4 -0.002592 -0.031991 -0.046641

#### Enter your answer here:




Now explore the data. Scikit-learn typically takes in 2D numpy arrays as input (though pandas dataframes are also accepted). In the cell below find the shape of the numpy array contained in the data portion of the diabetes variable.

In [9]:
# Your code here:
diabetes.shape

(442, 10)

# Challenge 2 - Perform Supervised Learning on the Dataset

#### The data has already been split to predictor and response variables. The response variable is in the `target` portion of the variable. 

Given this information, let's apply what we have previously learned about linear regression and apply the algorithm to the diabetes dataset. In the cell below, import the linear regression class from sklearn. 

In [12]:
# Your code here:
diabetes['target']=load_diabetes().target
diabetes.head()

age       sex       bmi        bp        s1        s2        s3  \
0  0.038076  0.050680  0.061696  0.021872 -0.044223 -0.034821 -0.043401   
1 -0.001882 -0.044642 -0.051474 -0.026328 -0.008449 -0.019163  0.074412   
2  0.085299  0.050680  0.044451 -0.005671 -0.045599 -0.034194 -0.032356   
3 -0.089063 -0.044642 -0.011595 -0.036656  0.012191  0.024991 -0.036038   
4  0.005383 -0.044642 -0.036385  0.021872  0.003935  0.015596  0.008142   

         s4        s5        s6  target  
0 -0.002592  0.019908 -0.017646   151.0  
1 -0.039493 -0.068330 -0.092204    75.0  
2 -0.002592  0.002864 -0.025930   141.0  
3  0.034309  0.022692 -0.009362   206.0  
4 -0.002592 -0.031991 -0.046641   135.0

In [15]:
diabetes.shape

(442, 11)

In [14]:
lr = LinearRegression()

Initialize the model in the variable `diabetes_model`

In [20]:
# Your code here:
X = diabetes.drop('target', axis = 1)
y = diabetes.target


In [23]:
diabetes_test = lr.fit(X = X, y = y)

In [24]:
diabetes_test

LinearRegression()

In the cell below, fit the model and print the intercept and coefficients of the model. 

In [25]:
# Your code here:
beta_1 = diabetes_test.coef_[0]
beta_0 = diabetes_test.intercept_


In [26]:
beta_1, beta_0

(-10.01219781747109, 152.1334841628965)

# Bonus Challenge 1 - Conduct a Hypothesis Test on the Model

Once we have generated a linear model, we can test each coefficient using a t-test to see whether the confidence interval for the variable contains zero. We can also perform an overall F test to check whether at least one coefficient is significantly different from zero. 

Refer to the resource in this [link](https://onlinecourses.science.psu.edu/stat501/node/297/) for more details and perform the t-tests for the model above. Additionally, interpret the results and list coefficients are significantly different from zero.


Hint: use the statsmodels package.

Your result should look similar to this:

![ols](../ols-results.png)

In [182]:
# Your code here:



# Challenge 2 - Peform Supervised Learning on a Pandas Dataframe

Now that we have looked at data that has been formatted for scikit-learn, let's look at data that we will need to format ourselves.

In the next cell, load the `auto-mpg.csv` file included in this folder and assign it to a variable called `auto`.

In [37]:
# Your code here:

auto = pd.read_csv('../auto-mpg.csv')

Look at the first 5 rows using the `head()` function:

In [38]:
# Your code here:
auto.head()

mpg  cylinders  displacement  horse_power  weight  acceleration  \
0  18.0          8         307.0        130.0    3504          12.0   
1  15.0          8         350.0        165.0    3693          11.5   
2  18.0          8         318.0        150.0    3436          11.0   
3  16.0          8         304.0        150.0    3433          12.0   
4  17.0          8         302.0        140.0    3449          10.5   

   model_year                       car_name  
0          70  \t"chevrolet chevelle malibu"  
1          70          \t"buick skylark 320"  
2          70         \t"plymouth satellite"  
3          70              \t"amc rebel sst"  
4          70                \t"ford torino"

Evaluate the data to ensure that all numeric columns are correctly detected as such by pandas. If a column is misclassified as object, coerce it to numeric.

In [39]:
# Your code here:
auto.dtypes
# car name is the only one which is not a number, we might as well drop it, it is not useful

mpg             float64
cylinders         int64
displacement    float64
horse_power     float64
weight            int64
acceleration    float64
model_year        int64
car_name         object
dtype: object

In [40]:
auto.drop('car_name', axis = 1, inplace = True)


In [41]:
auto.head()

mpg  cylinders  displacement  horse_power  weight  acceleration  \
0  18.0          8         307.0        130.0    3504          12.0   
1  15.0          8         350.0        165.0    3693          11.5   
2  18.0          8         318.0        150.0    3436          11.0   
3  16.0          8         304.0        150.0    3433          12.0   
4  17.0          8         302.0        140.0    3449          10.5   

   model_year  
0          70  
1          70  
2          70  
3          70  
4          70

In [67]:
auto.shape

(392, 7)

What is the newest model year and the oldest model year?

In [42]:
# Your code here:
auto.model_year.max()

82

In [43]:
auto.model_year.min()

70

Check the dataset for missing values and remove all rows containing at least one missing value.

In [53]:
# Your code here:
auto.isnull().sum()

mpg             0
cylinders       0
displacement    0
horse_power     6
weight          0
acceleration    0
model_year      0
dtype: int64

In [55]:
is_NaN = auto.isnull()
row_has_NaN = is_NaN.any(axis=1)
rows_with_NaN = auto[row_has_NaN]
print(rows_with_NaN)

      mpg  cylinders  displacement  horse_power  weight  acceleration  \
32   25.0          4          98.0          NaN    2046          19.0   
126  21.0          6         200.0          NaN    2875          17.0   
330  40.9          4          85.0          NaN    1835          17.3   
336  23.6          4         140.0          NaN    2905          14.3   
354  34.5          4         100.0          NaN    2320          15.8   
374  23.0          4         151.0          NaN    3035          20.5   

     model_year  
32           71  
126          74  
330          80  
336          80  
354          81  
374          82  


In [56]:
# we have to delete rows 32, 126, 330, 336, 354 and 374

In [58]:
auto.drop(auto.index[[32, 126, 330, 336, 354, 374]], inplace = True)

Find the frequency table for the `cylinders` column using the `value_counts()` function. How many possible values of cylinders are there?

In [61]:
# Your code here:
auto.cylinders.value_counts()
# 4 cylinders(most common), 8 cylinders, 6, 3 and 5 cylinders

4    199
8    103
6     83
3      4
5      3
Name: cylinders, dtype: int64

We would like to generate a linear regression model that will predict mpg. To do this, first drop the `car_name` column since it does not contain any quantitative data. Next separate the dataframe to predictor and response variables. Separate those into test and training data with 80% of the data in the training set and the remainder in the test set. 

Assign the predictor and response training data to `X_train` and `y_train` respectively. Similarly, assign the predictor and response test data to `X_test` and `y_test`.

In [69]:
X = auto.drop('mpg', axis=1)
y = auto.mpg

In [70]:
X.shape

(392, 6)

In [71]:
y.shape

(392,)

In [72]:
# Import the necessary function
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=111)

In [74]:
X_train.shape

(313, 6)

In [75]:
y_train.shape

(313,)

In [76]:
X_test.shape

(79, 6)

In [77]:
y_test.shape

(79,)

Now we will the dataset that we processed and peform linear regression on this data to predict the mpg for each vehicle. Initialize the model in the cell below.

In [100]:
# Your code here:
lr = LinearRegression()
auto_model = lr.fit(X_train, y_train)

In [101]:
pd.Series(auto_model.coef_, index=X.columns) #la relacion que tengo (scatterplot) con la target. Estas van an las X

cylinders       0.053014
displacement    0.000583
horse_power    -0.004927
weight         -0.006637
acceleration    0.099599
model_year      0.774439
dtype: float64

In [81]:
auto_train.intercept_

-16.965169985197285

# Challenge 3 - Evaluate the Model

the r squared score of a model tells us how much variation is explained by the model. In a typical dataset, most observations differ from the mean. When we create a model, we are trying to generate an equation that will tell us by how much each observation will differ from the mean. Obviously, the vast majority of models are not perfect. They can only predict some of the variation from the mean but not all of it. We attribute the rest of the difference between the actual value and the mean to random error. We would like random error to explain the as little as possible of the variation. This is why the r squared score is an important metric.

In the next cell, compute the r squared score of the model. Do this by first computing the predicted values and assign them to `y_pred`.

In [84]:
# Import the necessary function:
y_pred = lr.predict(X_test)
y_pred[:10]

array([ 7.38288127, 11.64382038, 28.76537552, 30.60135313, 23.17829674,
       28.78565661, 27.79021352, 23.19862546, 25.62089625, 21.19056495])

In [85]:
# Your code here:
y_test[:10]


95     12.0
116    16.0
273    23.9
195    29.0
194    22.5
142    26.0
147    24.0
264    18.1
243    21.5
100    18.0
Name: mpg, dtype: float64

#### Our next step is to evaluate the model using the test data. We would like to ensure that our model is not overfitting the data. This means that our model will not be able to generalize well outside of the training data.

In the cell below, use the model to generate the predicted values for the training data and assign them to `y_test_pred`. Compute the r squared score for the test data by comparing the oberserved `y_test` data and the predicted `y_test_pred`.

In [90]:
# Your code here:
metrics.r2_score(y_test, y_pred).round(3) # it is good

0.805

# Challenge 4 - Improve the Model Fit

While the most common way to improve the fit of a model is by using regularization, there are other simpler ways to improve model fit. The first is to create a simpler model. The second is to increase the train sample size.

Let us start with the easier option and increase our train sample size to 90% of the data. Create a new test train split and name the new predictors and response variables `X_train09`, `X_test09`, `y_train09`, `y_test09`.

In [91]:
# Your code here:
X_train09, X_test09, y_train09, y_test09 = train_test_split(X, y, test_size=0.1, random_state=111)


Initialize a new model. Name this model `auto_model09`. Fit the model to the new sample data.

In [92]:
# Your code here:
auto_model09 = lr.fit(X_train09, y_train09)


Compute the predicted values and r squared score for our new model and new sample data.

In [95]:
# Your code here:
y_pred09 = lr.predict(X_test09)
y_pred09[:10]

array([ 7.97106163, 12.12481835, 28.82780505, 30.41247869, 23.04410334,
       28.6798074 , 27.74498722, 22.95425858, 25.85946109, 21.1610464 ])

In [96]:
y_test09[:10]

95     12.0
116    16.0
273    23.9
195    29.0
194    22.5
142    26.0
147    24.0
264    18.1
243    21.5
100    18.0
Name: mpg, dtype: float64

Compute the r squared score for the smaller test set. Is there an improvement in the test r squared?

In [97]:
metrics.r2_score(y_test09, y_pred09).round(3)

0.771

In [199]:
# Your code here:



# Bonus Challenge 2 - Backward Elimination 

The main way to produce a simpler linear regression model is to reduce the number of variables used in the model. In scikit-learn, we can do this by using recursive feature elimination. You can read more about RFE [here](https://scikit-learn.org/stable/modules/generated/sklearn.feature_selection.RFE.html).

In the next cell, we will import RFE

In [99]:
from sklearn.feature_selection import RFE
from sklearn.svm import SVR

Follow the documentation and initialize an RFE model using the `auto_model` linear regression model. Set `n_features_to_select=3`

In [102]:
# Your code here:
selector = RFE(auto_model, n_features_to_select=3, step=1)

Fit the model and print the ranking

In [106]:
# Your code here:
selector = selector.fit(X,y)
selector.ranking_
# me esta dando el ranking de cada columna, la columna 1 es numero 1, al columna 2 es la numero 2, la columna 3 es la numero 4..

array([1, 2, 4, 3, 1, 1])

In [105]:
X.columns

Index(['cylinders', 'displacement', 'horse_power', 'weight', 'acceleration',
       'model_year'],
      dtype='object')

Feature importance is ranked from most important (1) to least important (4). Generate a model with the three most important features. The features correspond to variable names. For example, feature 1 is `cylinders` and feature 2 is `displacement`.

Perform a test-train split on this reduced column data and call the split data `X_train_reduced`, `X_test_reduced`, `y_test_reduced`, `y_train_reduced`. Use an 80% split.

In [116]:
# Your code here: 
X_reduced = X.drop(['displacement', 'horse_power', 'weight'], axis = 1)
y = auto.mpg


In [118]:
X_train_reduced, X_test_reduced, y_train_reduced, y_test_reduced = train_test_split(X_reduced, y, test_size=0.2, random_state=111)


Generate a new model called `auto_model_reduced` and fit this model. Then proceed to compute the r squared score for the model. Did this cause an improvement in the r squared score?

In [119]:
auto_model_reduced = lr.fit(X_train_reduced, y_train_reduced)


In [121]:
y_pred_reduced = lr.predict(X_test_reduced)
y_pred_reduced[:10]

array([13.40598742, 13.3571162 , 29.62645745, 28.30198723, 22.05830076,
       26.52138561, 26.52138561, 17.318279  , 31.84659659, 19.67899662])

In [122]:
y_test_reduced

95     12.0
116    16.0
273    23.9
195    29.0
194    22.5
       ... 
251    20.2
201    18.5
160    17.0
210    19.0
50     28.0
Name: mpg, Length: 79, dtype: float64

In [123]:
metrics.r2_score(y_test_reduced, y_pred_reduced).round(3)

0.708